// Generated by CoffeeScript 1.10.0
var entryView, volunteerView;

window.EntryList = {};

EntryList.view = function() {
  return m('.entry-list', [
    m('h1', "all Entries"), m('a[href=/entries/new]', {
      config: m.route
    }, "Add new Entry"), Entry.all().map(entryView)
  ]);
};

entryView = function(entry) {
  var date;
  date = new Date(entry.enteredAt);
  return m('.entry', [m('label', "entered at: ", date.toString()), m('ul', entry.volunteers.map(volunteerView))]);
};

volunteerView = function(volunteer) {
  return m('li.volunteer', [m('label', volunteer.name), m('label', "(" + volunteer.email + ")")]);
};
