// Generated by CoffeeScript 1.10.0
var idCounter, store;

window.Entry = {};

store = [];

idCounter = 1;

Entry.all = function() {
  return store;
};

Entry.create = function(attrs) {
  attrs.id = (idCounter += 1);
  attrs.enteredAt = Date.now();
  store.push(attrs);
};
